<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FosUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUsersRepository extends EntityRepository
{
}
